// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDauwDCFrO6S4KDnsISa1KAZTxlky8ij58',
    appId: '1:767729099088:web:3d0cee7ea2152dbcd0cc55',
    messagingSenderId: '767729099088',
    projectId: 'chatapp-8e1ef',
    authDomain: 'chatapp-8e1ef.firebaseapp.com',
    storageBucket: 'chatapp-8e1ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiSBruyWSaLUxHxnd_VO1bJmXUKgdaQM',
    appId: '1:767729099088:android:4f42602c846d5659d0cc55',
    messagingSenderId: '767729099088',
    projectId: 'chatapp-8e1ef',
    storageBucket: 'chatapp-8e1ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2Wcm6Zljz3rKJChURtE5wLLuYY44jL4',
    appId: '1:767729099088:ios:8301e60ca080c8a0d0cc55',
    messagingSenderId: '767729099088',
    projectId: 'chatapp-8e1ef',
    storageBucket: 'chatapp-8e1ef.appspot.com',
    iosBundleId: 'com.example.rxdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2Wcm6Zljz3rKJChURtE5wLLuYY44jL4',
    appId: '1:767729099088:ios:8301e60ca080c8a0d0cc55',
    messagingSenderId: '767729099088',
    projectId: 'chatapp-8e1ef',
    storageBucket: 'chatapp-8e1ef.appspot.com',
    iosBundleId: 'com.example.rxdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDauwDCFrO6S4KDnsISa1KAZTxlky8ij58',
    appId: '1:767729099088:web:63718f5c5d8a16a7d0cc55',
    messagingSenderId: '767729099088',
    projectId: 'chatapp-8e1ef',
    authDomain: 'chatapp-8e1ef.firebaseapp.com',
    storageBucket: 'chatapp-8e1ef.appspot.com',
  );
}
